#!/command/with-contenv sh

echo " ____                            _ _             "
echo "/ ___|  ___  _ __ __ _ _ __ ___ (_) |_ ___ _   _ "
echo "\___ \ / _ \| '__/ _\` | '_ \` _ \| | __/ __| | | |"
echo " ___) | (_) | | | (_| | | | | | | | |_\__ \ |_| |"
echo "|____/ \___/|_|  \__,_|_| |_| |_|_|\__|___/\__,_|"
echo "                                                 "
echo "Network Time Protocol"
echo

# LOG_LEVEL environment variable is not present, so populate with chrony default (0)
# chrony log levels: 0 (informational), 1 (warning), 2 (non-fatal error) and 3 (fatal error)
if [ -z "${LOG_LEVEL}" ]; then
  LOG_LEVEL=0
else
  # confirm log level is between 0-3, since these are the only log levels supported
  if [ "${LOG_LEVEL}" -gt 3 ]; then
    # level outside of supported range, let's set to default (0)
    LOG_LEVEL=0
  fi
fi

## startup chronyd in the foreground
## Disabled control of system clock
/usr/sbin/chronyd -u chrony -d -x -L ${LOG_LEVEL}
